const campusData = {
  stats: [
    { label: 'Events This Week', value: 14, icon: '🎉' },
    { label: 'New Announcements', value: 9, icon: '📢' },
    { label: 'Library Resources', value: 1280, icon: '📚' },
    { label: 'Campus Facilities', value: 18, icon: '🏫' },
    { label: 'Active Clubs', value: 12, icon: '👥' },
    { label: 'Lost & Found', value: 7, icon: '🔎' },
    { label: 'Canteen Specials', value: 5, icon: '🍴' },
    { label: 'Student Interactions', value: 24, icon: '💬' }
  ],
  today: [
    { time: '09:00 AM', title: 'AI & ML Department Seminar', location: 'Seminar Hall' },
    { time: '11:30 AM', title: 'Coding Club Workshop', location: 'Lab 204' },
    { time: '01:00 PM', title: 'Canteen Special Lunch', location: 'Main Canteen' },
    { time: '03:30 PM', title: 'Basketball Practice', location: 'Sports Ground' },
    { time: '05:00 PM', title: 'Robotics Club Meetup', location: 'Innovation Hub' }
  ],
  events: [
    {
      id: "e1",
      title: "The Future of Cities: An Evening with Dr. Helena Marsh",
      category: "Lectures",
      start: "2026-10-08T18:30:00",
      end: "2026-10-08T20:00:00",
      date: "2026-10-08",
      time: "18:30 - 20:00",
      venue: "Aldridge Auditorium",
      host: "School of Architecture",
      organizer: "School of Architecture",
      summary: "The urbanist behind Copenhagen's car-free harbour plan on what campuses can teach cities about density, shared space and staying human at scale. Followed by an open Q&A.",
      description: "The urbanist behind Copenhagen's car-free harbour plan on what campuses can teach cities about density, shared space and staying human at scale. Followed by an open Q&A.",
      image: "assets/images/47f52d3a-89cf-411c-8a8a-b59027479ead.jpg",
      capacity: 420,
      registered: 371,
      seatsAvailable: 49,
      price: "Free",
      format: "Hybrid",
      featured: true,
      eligibility: "Open to all students, researchers and campus visitors.",
      registrationDeadline: "2026-10-07",
      contact: "architecture@campus360.edu"
    },
    {
      id: "e2",
      title: "Quad Sessions: Autumn Jazz Night",
      category: "Music",
      start: "2026-10-09T19:00:00",
      end: "2026-10-09T22:00:00",
      date: "2026-10-09",
      time: "19:00 - 22:00",
      venue: "Founders' Quad",
      host: "University Music Society",
      organizer: "University Music Society",
      summary: "Three student ensembles, string lights and hot cider on the lawn. Bring a blanket — the quad stays open until ten.",
      description: "Three student ensembles, string lights and hot cider on the lawn. Bring a blanket — the quad stays open until ten.",
      image: "assets/images/dd745b23-6888-450d-98ff-e3d6f3b46b25.jpg",
      capacity: 600,
      registered: 412,
      seatsAvailable: 188,
      price: "Free",
      format: "In person",
      featured: true,
      eligibility: "All students and campus community members.",
      registrationDeadline: "2026-10-09",
      contact: "music.society@campus360.edu"
    },
    {
      id: "e3",
      title: "Build Weekend: 24-Hour Hackathon",
      category: "Tech",
      start: "2026-10-16T18:00:00",
      end: "2026-10-17T18:00:00",
      date: "2026-10-16",
      time: "18:00 - 18:00 (+1d)",
      venue: "Library Atrium",
      host: "Computing Society",
      organizer: "Computing Society",
      summary: "Form a team of up to four and ship something useful for campus life. Mentors on hand overnight, meals included, demos Saturday afternoon.",
      description: "Form a team of up to four and ship something useful for campus life. Mentors on hand overnight, meals included, demos Saturday afternoon.",
      image: "assets/images/94f702b4-3248-4436-a7a3-aefb53235db5.jpg",
      capacity: 180,
      registered: 174,
      seatsAvailable: 6,
      price: "Free",
      format: "In person",
      featured: true,
      eligibility: "All student developers, designers, and project builders.",
      registrationDeadline: "2026-10-14",
      contact: "hackathon@campus360.edu"
    },
    {
      id: "e4",
      title: "Clay & Form: MFA Ceramics Opening",
      category: "Arts",
      start: "2026-10-06T17:30:00",
      end: "2026-10-06T20:00:00",
      date: "2026-10-06",
      time: "17:30 - 20:00",
      venue: "Hartley Gallery",
      host: "Department of Fine Art",
      organizer: "Department of Fine Art",
      summary: "Twelve graduating ceramicists open their thesis exhibition. Artists will be at their plinths for the first hour.",
      description: "Twelve graduating ceramicists open their thesis exhibition. Artists will be at their plinths for the first hour.",
      image: "assets/images/27eca19d-b2cd-49b1-8992-06934a87a3d3.jpg",
      capacity: 150,
      registered: 64,
      seatsAvailable: 86,
      price: "Free",
      format: "In person",
      eligibility: "Open to the general student body.",
      registrationDeadline: "2026-10-06",
      contact: "finearts@campus360.edu"
    },
    {
      id: "e5",
      title: "Head of the River: Varsity Regatta",
      category: "Sport",
      start: "2026-10-11T07:30:00",
      end: "2026-10-11T12:00:00",
      date: "2026-10-11",
      time: "07:30 - 12:00",
      venue: "Boathouse Lawn",
      host: "University Boat Club",
      organizer: "University Boat Club",
      summary: "The season's first home regatta. Watch from the lawn — breakfast stalls open at seven, finals start around eleven.",
      description: "The season's first home regatta. Watch from the lawn — breakfast stalls open at seven, finals start around eleven.",
      image: "assets/images/cbf91914-01d7-4a07-a063-fe808322b44c.jpg",
      capacity: 800,
      registered: 233,
      seatsAvailable: 567,
      price: "Free",
      format: "In person",
      eligibility: "Spectators and supporters welcome.",
      registrationDeadline: "2026-10-10",
      contact: "rowing@campus360.edu"
    },
    {
      id: "e6",
      title: "Careers Fair: Climate & Energy",
      category: "Careers",
      start: "2026-10-07T11:00:00",
      end: "2026-10-07T16:00:00",
      date: "2026-10-07",
      time: "11:00 - 16:00",
      venue: "Student Union Great Hall",
      host: "Careers Service",
      organizer: "Careers Service",
      summary: "Sixty employers from renewables, policy and climate tech. CV clinic runs alongside in the Blue Room.",
      description: "Sixty employers from renewables, policy and climate tech. CV clinic runs alongside in the Blue Room.",
      capacity: 1200,
      registered: 846,
      seatsAvailable: 354,
      price: "Free",
      format: "In person",
      eligibility: "All undergraduate and postgraduate students.",
      registrationDeadline: "2026-10-07",
      contact: "careers@campus360.edu"
    },
    {
      id: "e7",
      title: "Writing for Impact: Op-Ed Workshop",
      category: "Careers",
      start: "2026-10-05T14:00:00",
      end: "2026-10-05T15:30:00",
      date: "2026-10-05",
      time: "14:00 - 15:30",
      venue: "Seminar Room 2.14",
      host: "School of Journalism",
      organizer: "School of Journalism",
      summary: "A hands-on session with a national newspaper's opinion editor. Bring a 300-word draft for live feedback.",
      description: "A hands-on session with a national newspaper's opinion editor. Bring a 300-word draft for live feedback.",
      capacity: 30,
      registered: 30,
      seatsAvailable: 0,
      price: "Free",
      format: "In person",
      eligibility: "Limited seats, priority to humanities & media students.",
      registrationDeadline: "2026-10-04",
      contact: "journalism@campus360.edu"
    },
    {
      id: "e8",
      title: "Machine Learning Ethics, Explained",
      category: "Lectures",
      start: "2026-10-05T17:00:00",
      end: "2026-10-05T18:00:00",
      date: "2026-10-05",
      time: "17:00 - 18:00",
      venue: "Online",
      host: "Centre for Responsible AI",
      organizer: "Centre for Responsible AI",
      summary: "A one-hour primer on bias, consent and accountability in the models you already use every day.",
      description: "A one-hour primer on bias, consent and accountability in the models you already use every day.",
      capacity: 500,
      registered: 189,
      seatsAvailable: 311,
      price: "Free",
      format: "Online",
      eligibility: "Open to everyone online.",
      registrationDeadline: "2026-10-05",
      contact: "ai.ethics@campus360.edu"
    },
    {
      id: "e9",
      title: "International Food Night",
      category: "Community",
      start: "2026-10-10T18:00:00",
      end: "2026-10-10T21:00:00",
      date: "2026-10-10",
      time: "18:00 - 21:00",
      venue: "Commons Courtyard",
      host: "Global Students Association",
      organizer: "Global Students Association",
      summary: "Twenty-four home kitchens, one courtyard. Your ticket covers five tasting plates.",
      description: "Twenty-four home kitchens, one courtyard. Your ticket covers five tasting plates.",
      capacity: 350,
      registered: 341,
      seatsAvailable: 9,
      price: "£3",
      format: "In person",
      eligibility: "Open to students and guests.",
      registrationDeadline: "2026-10-09",
      contact: "global@campus360.edu"
    },
    {
      id: "e10",
      title: "Chamber Choir: Choral Evensong",
      category: "Music",
      start: "2026-10-12T18:00:00",
      end: "2026-10-12T19:00:00",
      date: "2026-10-12",
      time: "18:00 - 19:00",
      venue: "University Chapel",
      host: "Chapel Choir",
      organizer: "Chapel Choir",
      summary: "Tallis, Howells and a new commission by second-year composer Mei Lin.",
      description: "Tallis, Howells and a new commission by second-year composer Mei Lin.",
      capacity: 220,
      registered: 98,
      seatsAvailable: 122,
      price: "Free",
      format: "In person",
      eligibility: "All are welcome.",
      registrationDeadline: "2026-10-12",
      contact: "chapel@campus360.edu"
    },
    {
      id: "e11",
      title: "Open Mic Poetry",
      category: "Arts",
      start: "2026-10-13T20:00:00",
      end: "2026-10-13T22:00:00",
      date: "2026-10-13",
      time: "20:00 - 22:00",
      venue: "The Cellar Bar",
      host: "Creative Writing Society",
      organizer: "Creative Writing Society",
      summary: "Five-minute slots, sign-up on the night. Listeners very welcome.",
      description: "Five-minute slots, sign-up on the night. Listeners very welcome.",
      capacity: 80,
      registered: 52,
      seatsAvailable: 28,
      price: "Free",
      format: "In person",
      eligibility: "Open mic performers and listeners.",
      registrationDeadline: "2026-10-13",
      contact: "writing@campus360.edu"
    },
    {
      id: "e12",
      title: "Office Hours with Alumni Founders",
      category: "Careers",
      start: "2026-10-14T12:00:00",
      end: "2026-10-14T14:00:00",
      date: "2026-10-14",
      time: "12:00 - 14:00",
      venue: "Innovation Hub",
      host: "Enterprise Centre",
      organizer: "Enterprise Centre",
      summary: "Fifteen-minute one-to-ones with founders who started their companies on campus.",
      description: "Fifteen-minute one-to-ones with founders who started their companies on campus.",
      capacity: 40,
      registered: 37,
      seatsAvailable: 3,
      price: "Free",
      format: "Hybrid",
      eligibility: "Aspiring student entrepreneurs.",
      registrationDeadline: "2026-10-13",
      contact: "enterprise@campus360.edu"
    },
    {
      id: "e13",
      title: "Five-a-Side League Draw",
      category: "Sport",
      start: "2026-10-14T18:00:00",
      end: "2026-10-14T19:00:00",
      date: "2026-10-14",
      time: "18:00 - 19:00",
      venue: "Sports Centre, Pitch 3",
      host: "Athletic Union",
      organizer: "Athletic Union",
      summary: "Register a team or join as a free agent. Fixtures start the following week.",
      description: "Register a team or join as a free agent. Fixtures start the following week.",
      capacity: 120,
      registered: 70,
      seatsAvailable: 50,
      price: "Free",
      format: "In person",
      eligibility: "All matriculated students.",
      registrationDeadline: "2026-10-14",
      contact: "sports@campus360.edu"
    },
    {
      id: "e14",
      title: "Robotics Lab Open Day",
      category: "Tech",
      start: "2026-10-15T10:00:00",
      end: "2026-10-15T15:00:00",
      date: "2026-10-15",
      time: "10:00 - 15:00",
      venue: "Engineering Building",
      host: "Faculty of Engineering",
      organizer: "Faculty of Engineering",
      summary: "Drive a rover, meet the quadruped team and see the soft-robotics bench up close.",
      description: "Drive a rover, meet the quadruped team and see the soft-robotics bench up close.",
      capacity: 300,
      registered: 120,
      seatsAvailable: 180,
      price: "Free",
      format: "In person",
      eligibility: "Open to all students and faculty.",
      registrationDeadline: "2026-10-15",
      contact: "robotics@campus360.edu"
    },
    {
      id: "e15",
      title: "Wellbeing Walk: Arboretum Loop",
      category: "Community",
      start: "2026-10-17T09:00:00",
      end: "2026-10-17T10:30:00",
      date: "2026-10-17",
      time: "09:00 - 10:30",
      venue: "West Gate",
      host: "Student Wellbeing",
      organizer: "Student Wellbeing",
      summary: "A gentle 5km loop through the arboretum at peak autumn colour. Coffee after.",
      description: "A gentle 5km loop through the arboretum at peak autumn colour. Coffee after.",
      capacity: 40,
      registered: 12,
      seatsAvailable: 28,
      price: "Free",
      format: "In person",
      eligibility: "Open to all students and staff.",
      registrationDeadline: "2026-10-16",
      contact: "wellbeing@campus360.edu"
    },
    {
      id: "e16",
      title: "Film Society: Agnès Varda Double Bill",
      category: "Arts",
      start: "2026-10-07T19:30:00",
      end: "2026-10-07T23:00:00",
      date: "2026-10-07",
      time: "19:30 - 23:00",
      venue: "Lecture Theatre B",
      host: "Film Society",
      organizer: "Film Society",
      summary: "Cléo from 5 to 7 and The Gleaners and I, introduced by Prof. Anika Rao.",
      description: "Cléo from 5 to 7 and The Gleaners and I, introduced by Prof. Anika Rao.",
      capacity: 160,
      registered: 91,
      seatsAvailable: 69,
      price: "£4",
      format: "In person",
      eligibility: "Film society members and general audience.",
      registrationDeadline: "2026-10-07",
      contact: "filmsoc@campus360.edu"
    },
    {
      id: "evt-1",
      title: "AI & Machine Learning Workshop",
      category: "Tech",
      start: "2026-10-12T11:00:00",
      end: "2026-10-12T13:00:00",
      date: "2026-10-12",
      time: "11:00 - 13:00",
      venue: "Seminar Hall",
      host: "AI/ML Club",
      organizer: "AI/ML Club",
      summary: "Hands-on workshop on building practical AI prototypes and moving from theory to deployment.",
      description: "Hands-on workshop on building practical AI prototypes and moving from theory to deployment.",
      eligibility: "Open to all students with interest in AI, ML, and automation.",
      registrationDeadline: "2026-10-10",
      capacity: 60,
      registered: 12,
      seatsAvailable: 48,
      price: "Free",
      format: "In person",
      contact: "ai.club@campus360.edu"
    },
    {
      id: "evt-2",
      title: "Inter-Department Football Championship",
      category: "Sport",
      start: "2026-10-15T16:00:00",
      end: "2026-10-15T18:30:00",
      date: "2026-10-15",
      time: "16:00 - 18:30",
      venue: "Sports Ground",
      host: "Sports Committee",
      organizer: "Sports Committee",
      summary: "A competitive in-campus football championship with team spirit and student engagement.",
      description: "A competitive in-campus football championship with team spirit and student engagement.",
      eligibility: "Students from all departments may register as teams.",
      registrationDeadline: "2026-10-13",
      capacity: 150,
      registered: 30,
      seatsAvailable: 120,
      price: "Free",
      format: "In person",
      contact: "sports@campus360.edu"
    },
    {
      id: "evt-3",
      title: "Designing Your First Web App",
      category: "Tech",
      start: "2026-10-20T14:30:00",
      end: "2026-10-20T16:30:00",
      date: "2026-10-20",
      time: "14:30 - 16:30",
      venue: "Lab 302",
      host: "Computer Engineering Department",
      organizer: "Computer Engineering Department",
      summary: "An introductory session on frontend planning, layout principles, and functional interactions.",
      description: "An introductory session on frontend planning, layout principles, and functional interactions.",
      eligibility: "Beginner-friendly for first and second year students.",
      registrationDeadline: "2026-10-18",
      capacity: 80,
      registered: 15,
      seatsAvailable: 65,
      price: "Free",
      format: "Hybrid",
      contact: "webops@campus360.edu"
    },
    {
      id: "evt-4",
      title: "Cultural Night 2026",
      category: "Music",
      start: "2026-10-23T19:00:00",
      end: "2026-10-23T22:00:00",
      date: "2026-10-23",
      time: "19:00 - 22:00",
      venue: "Auditorium",
      host: "Cultural Club",
      organizer: "Cultural Club",
      summary: "A vibrant evening of music, dance, drama, and student performances.",
      description: "A vibrant evening of music, dance, drama, and student performances.",
      eligibility: "All students are welcome.",
      registrationDeadline: "2026-10-21",
      capacity: 250,
      registered: 50,
      seatsAvailable: 200,
      price: "Free",
      format: "In person",
      contact: "culture@campus360.edu"
    },
    {
      id: "evt-5",
      title: "Placement Preparation Bootcamp",
      category: "Careers",
      start: "2026-10-28T10:00:00",
      end: "2026-10-28T13:00:00",
      date: "2026-10-28",
      time: "10:00 - 13:00",
      venue: "Seminar Hall",
      host: "Career Cell",
      organizer: "Career Cell",
      summary: "Resume review, aptitude practice, and mock interview readiness for graduating students.",
      description: "Resume review, aptitude practice, and mock interview readiness for graduating students.",
      eligibility: "Final year students and interested pre-final year students.",
      registrationDeadline: "2026-10-25",
      capacity: 100,
      registered: 15,
      seatsAvailable: 85,
      price: "Free",
      format: "In person",
      contact: "placements@campus360.edu"
    }
  ],
  announcements: [
    { id: 'ann-1', title: 'Library extended hours during internal assessments', category: 'Academic', priority: 'Important', department: 'Library', date: '2026-10-01', description: 'The library remains open until 9:30 PM for the next two weeks to support revision and exam preparation.', attachment: true, read: false },
    { id: 'ann-2', title: 'Mid-semester exam schedule released', category: 'Examination', priority: 'Urgent', department: 'Exam Cell', date: '2026-10-02', description: 'Please check the updated timetable and seating arrangement for the upcoming mid-semester tests.', attachment: true, read: false },
    { id: 'ann-3', title: 'Free Wi-Fi upgrade in academic blocks', category: 'Administration', priority: 'Normal', department: 'IT Services', date: '2026-10-03', description: 'Wireless connectivity has been improved in Blocks A, B and the central lobby during maintenance.', attachment: false, read: true },
    { id: 'ann-4', title: 'Placement drive registration open', category: 'Placement', priority: 'Important', department: 'Career Cell', date: '2026-10-04', description: 'Students interested in the software role drive should submit their CVs by the end of this week.', attachment: true, read: false },
    { id: 'ann-5', title: 'Student activity fair registrations live', category: 'Student Affairs', priority: 'Normal', department: 'Student Council', date: '2026-10-05', description: 'All clubs can register for the semester activity fair and showcase their events for new students.', attachment: false, read: true },
    { id: 'ann-6', title: 'AI/ML lab access update', category: 'Department', priority: 'Normal', department: 'AI & ML', date: '2026-10-06', description: 'Students must carry their ID cards while using the research labs after 4:00 PM.', attachment: false, read: false }
  ],
  news: [
    { id: 'news-1', title: 'Campus innovation fair brings student prototypes to life', category: 'Student Achievements', summary: 'A vibrant showcase of projects from design, engineering and AI-based student teams.', date: '2026-10-01', author: 'Campus Desk', readingTime: '4 min read', image: 'linear-gradient(135deg, rgba(37,99,235,0.14), rgba(20,184,166,0.14))' },
    { id: 'news-2', title: 'New digital library catalog now available to all students', category: 'Infrastructure', summary: 'The library has introduced a searchable digital catalog with quick access to new editions and e-books.', date: '2026-09-28', author: 'Library Team', readingTime: '3 min read', image: 'linear-gradient(135deg, rgba(6,182,212,0.2), rgba(124,58,237,0.18))' },
    { id: 'news-3', title: 'Faculty team experiments with sustainable campus design', category: 'Faculty Achievement', summary: 'A collaborative effort on greener campus systems and design-driven energy savings.', date: '2026-09-23', author: 'Research Office', readingTime: '5 min read', image: 'linear-gradient(135deg, rgba(16,185,129,0.14), rgba(59,130,246,0.16))' },
    { id: 'news-4', title: 'NSS drives cleanliness and social outreach initiative', category: 'Campus Initiatives', summary: 'Volunteers teamed up to improve public spaces and support community outreach programs.', date: '2026-09-18', author: 'NSS Cell', readingTime: '4 min read', image: 'linear-gradient(135deg, rgba(250,204,21,0.18), rgba(251,146,60,0.16))' }
  ],
  blogs: [
    { id: 'blog-1', title: 'Finding your rhythm in a packed engineering semester', author: 'Aarav S.', role: 'Student', date: '2026-09-15', readingTime: '6 min read', category: 'Student Life', excerpt: 'A practical guide to balancing projects, assignments, and personal time without burning out.', cover: 'linear-gradient(135deg, rgba(59,130,246,0.18), rgba(14,165,233,0.2))' },
    { id: 'blog-2', title: 'What makes a strong first-year portfolio?', author: 'Meera K.', role: 'Mentor', date: '2026-09-18', readingTime: '5 min read', category: 'Career', excerpt: 'Learn how to showcase projects, internships, and skills in a way that attracts attention.', cover: 'linear-gradient(135deg, rgba(124,58,237,0.18), rgba(59,130,246,0.18))' },
    { id: 'blog-3', title: 'From campus club to community project', author: 'Yash R.', role: 'Robotics Club Member', date: '2026-09-22', readingTime: '7 min read', category: 'Clubs', excerpt: 'A story of turning curiosity into a team-driven robotics initiative.', cover: 'linear-gradient(135deg, rgba(16,185,129,0.16), rgba(20,184,166,0.18))' }
  ],
  books: [
    { id: 'book-1', title: 'Data Structures and Algorithms', author: 'S. Chand', category: 'Programming', availability: 'Available', shelf: 'A-12', isbn: '978-1-234-56789-0', publisher: 'Campus Press', description: 'A foundational guide covering core data structures, algorithmic thinking and problem-solving techniques.', edition: '3rd Edition' },
    { id: 'book-2', title: 'Machine Learning Fundamentals', author: 'R. Verma', category: 'AI/ML', availability: 'Issued', shelf: 'B-04', isbn: '978-1-234-56789-1', publisher: 'Academic House', description: 'Covers comparing models, training, validation and practical ML workflows for students.', edition: '2nd Edition' },
    { id: 'book-3', title: 'Engineering Mathematics', author: 'P. Sharma', category: 'Engineering', availability: 'Available', shelf: 'C-11', isbn: '978-1-234-56789-2', publisher: 'Core Concepts', description: 'Useful for solving ordinary differential equations, probability, and matrices in engineering.', edition: '5th Edition' },
    { id: 'book-4', title: 'Operating Systems', author: 'N. Mehta', category: 'Reference', availability: 'Available', shelf: 'D-09', isbn: '978-1-234-56789-3', publisher: 'Tech Library', description: 'Covers process management, memory, scheduling and file systems in detail.', edition: '1st Edition' },
    { id: 'book-5', title: 'Creative Writing Essentials', author: 'J. Patel', category: 'Fiction', availability: 'E-book', shelf: 'E-02', isbn: '978-1-234-56789-4', publisher: 'Ink & Paper', description: 'A student-friendly guide to storytelling, vocabulary-building and narrative voice.', edition: '4th Edition' }
  ],
  canteen: [
    { id: 'food-1', name: 'Veg Poha', category: 'Breakfast', price: 35, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(22,163,74,0.15), rgba(16,185,129,0.16))' },
    { id: 'food-2', name: 'Paneer Sandwich', category: 'Breakfast', price: 60, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(59,130,246,0.15), rgba(139,92,246,0.15))' },
    { id: 'food-3', name: 'Dal Tadka', category: 'Lunch', price: 90, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(234,179,8,0.18), rgba(249,115,22,0.12))' },
    { id: 'food-4', name: 'Butter Naan + Paneer Masala', category: 'Lunch', price: 145, veg: true, availability: 'Limited', image: 'linear-gradient(135deg, rgba(251,146,60,0.18), rgba(239,68,68,0.12))' },
    { id: 'food-5', name: 'Veg Spring Roll', category: 'Snacks', price: 50, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(6,182,212,0.14), rgba(14,165,233,0.16))' },
    { id: 'food-6', name: 'Cold Coffee', category: 'Beverages', price: 55, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(251,191,36,0.15), rgba(249,115,22,0.12))' },
    { id: 'food-7', name: 'Masala Dosa', category: 'Lunch', price: 70, veg: true, availability: 'Available', image: 'linear-gradient(135deg, rgba(16,185,129,0.12), rgba(34,197,94,0.18))' },
    { id: 'food-8', name: 'Special Thali', category: 'Specials', price: 160, veg: true, availability: 'Popular', image: 'linear-gradient(135deg, rgba(37,99,235,0.16), rgba(124,58,237,0.16))' }
  ],
  clubs: [
    { id: 'club-1', name: 'Coding Club', category: 'Technical', members: 220, upcoming: 'Hacknight on Friday', description: 'A collaborative community for problem-solving, web development and hackathons.', contact: '@codingclub', logo: '💻' },
    { id: 'club-2', name: 'AI/ML Club', category: 'Technical', members: 180, upcoming: 'Computer Vision Demo', description: 'Explores machine learning workflows, research discussions, and projects.', contact: '@aimlclub', logo: '🤖' },
    { id: 'club-3', name: 'Robotics Club', category: 'Technical', members: 150, upcoming: 'Robot Build Session', description: 'Hands-on building and experimentation with robotics and embedded systems.', contact: '@roboticsclub', logo: '🛠️' },
    { id: 'club-4', name: 'Literary Club', category: 'Arts', members: 110, upcoming: 'Open Mic Evening', description: 'Encourages creative writing, discussions, and expressive storytelling.', contact: '@literaryclub', logo: '📖' },
    { id: 'club-5', name: 'Cultural Club', category: 'Arts', members: 200, upcoming: 'Dance Fusion Workshop', description: 'Celebrates identity, performance, and campus culture through creative arts.', contact: '@culturalclub', logo: '🎭' },
    { id: 'club-6', name: 'Sports Club', category: 'Sports', members: 260, upcoming: 'Inter-college tournament prep', description: 'A hub for sports practice, match planning and sportsmanship.', contact: '@sportsclub', logo: '🏅' }
  ],
  departments: [
    { id: 'dept-1', name: 'Computer Engineering', overview: 'Software systems, coding culture, and practical engineering fundamentals.', labs: 'Programming Lab, Networking Lab', events: 'Hackathons, startup workshops', contact: 'ce@demo-campus.edu' },
    { id: 'dept-2', name: 'Artificial Intelligence & Machine Learning', overview: 'Research and project work in AI, deep learning and intelligent systems.', labs: 'AI Lab, Data Science Lab', events: 'ML challenge, research showcase', contact: 'aiml@demo-campus.edu' },
    { id: 'dept-3', name: 'Information Technology', overview: 'Digital systems, application design, and cloud-based technology workflows.', labs: 'Web Lab, IT Infrastructure Lab', events: 'IT fair, cloud bootcamps', contact: 'it@demo-campus.edu' },
    { id: 'dept-4', name: 'Mechanical Engineering', overview: 'Applied mechanics, manufacturing and design-thinking for physical systems.', labs: 'Workshop, CAD Lab', events: 'Innovation expo, technical seminars', contact: 'mech@demo-campus.edu' },
    { id: 'dept-5', name: 'Civil Engineering', overview: 'Structures, surveying and sustainable infrastructure approaches.', labs: 'Surveying Lab, Material Testing Lab', events: 'Site visits, model competitions', contact: 'civil@demo-campus.edu' }
  ],
  facilities: [
    { id: 'fac-1', name: 'Library', location: 'Central Block', hours: '8:30 AM - 8:30 PM', description: 'Study zones, archives, and book lending services for academic and research support.', features: ['Reading rooms', 'Reference desk', 'E-books'] },
    { id: 'fac-2', name: 'Computer Labs', location: 'Block B, Floor 2', hours: '9:00 AM - 6:00 PM', description: 'Lab infrastructure for coding, simulations, graphics, and practical coursework.', features: ['High-speed PCs', 'Programming tools', 'Project labs'] },
    { id: 'fac-3', name: 'Auditorium', location: 'Main Campus', hours: '9:00 AM - 8:00 PM', description: 'Large event venue for seminars, cultural programs, and larger gatherings.', features: ['Stage lighting', 'Audio system', 'Seating for 250+'] },
    { id: 'fac-4', name: 'Seminar Hall', location: 'Academic Block', hours: '9:00 AM - 5:00 PM', description: 'Discussion and lecture space for workshops, guest sessions and presentations.', features: ['Projectors', 'AV setup', 'Lecture seating'] },
    { id: 'fac-5', name: 'Canteen', location: 'Student Plaza', hours: '8:00 AM - 7:00 PM', description: 'Students can access daily meals, snacks, beverages, and special items.', features: ['Veg menu', 'Combo meals', 'Quick snacks'] },
    { id: 'fac-6', name: 'Sports Ground', location: 'South Campus', hours: '6:00 AM - 7:00 PM', description: 'Sports and physical activities for football, athletics, and practice sessions.', features: ['Ground access', 'Practice kits', 'Open courts'] }
  ],
  lostFound: [
    { id: 'lf-1', itemName: 'Black ID Card', category: 'ID Card', description: 'Found near the library entrance during lunchtime.', location: 'Library', date: '2026-10-01', status: 'Found', contact: 'securitydesk@demo-campus.edu' },
    { id: 'lf-2', itemName: 'Blue Wallet', category: 'Wallet', description: 'A blue leather wallet with student ID and a few notes was found in the canteen.', location: 'Canteen', date: '2026-09-29', status: 'Unclaimed', contact: 'canteenhelp@demo-campus.edu' },
    { id: 'lf-3', itemName: 'Gray USB-C Charger', category: 'Charger', description: 'Lost in the computer lab after 4PM.', location: 'Lab 205', date: '2026-09-27', status: 'Lost', contact: 'labhelp@demo-campus.edu' }
  ],
  notifications: [
    { id: 'not-1', text: 'New announcement: library hours extended during assessments.', time: '2m ago', read: false },
    { id: 'not-2', text: 'Your event registration for AI Workshop is confirmed.', time: '12m ago', read: false },
    { id: 'not-3', text: 'Feedback received successfully. Thank you for sharing your input.', time: '1h ago', read: true },
    { id: 'not-4', text: 'Order #C360-1042 is now being prepared.', time: '2h ago', read: true }
  ],
  calendarEvents: [
    { date: '2026-10-05', title: 'Mid-semester exam', type: 'Exam' },
    { date: '2026-10-08', title: 'Placement drive', type: 'Placement' },
    { date: '2026-10-12', title: 'AI workshop', type: 'Event' },
    { date: '2026-10-15', title: 'Football championship', type: 'Sports' },
    { date: '2026-10-19', title: 'Holiday', type: 'Holiday' },
    { date: '2026-10-20', title: 'Web app workshop', type: 'Workshop' },
    { date: '2026-10-23', title: 'Cultural night', type: 'Event' }
  ],
  timetable: [
    { day: 'Monday', subjects: [
      { time: '09:00 - 10:00', subject: 'Data Structures', room: 'Room 201', faculty: 'Dr. Rao' },
      { time: '10:15 - 11:15', subject: 'Web Design', room: 'Lab 204', faculty: 'Ms. Jain' },
      { time: '01:30 - 02:30', subject: 'Algorithms', room: 'Room 305', faculty: 'Prof. Sen' }
    ] },
    { day: 'Tuesday', subjects: [
      { time: '09:00 - 10:00', subject: 'AI Basics', room: 'Room 112', faculty: 'Dr. Rao' },
      { time: '12:00 - 01:00', subject: 'Operating Systems', room: 'Room 204', faculty: 'Ms. Oza' }
    ] }
  ]
};

window.campusData = campusData;
